### ISSUE TITLE
Temporary Tables

### ISSUE THREAD

**Issue by SabineWren** [jacentino/SqlFun#11]
Hi, I started using SqlFun yesterday. It works great so far for Select and Upsert queries.

### Question
Is it possible to use temporary tables with SqlFun? It's throwing an exception, but my query works in Dapper and Azure Data Studio.
```
ClassName: "System.Data.SqlClient.SqlException",
Message: "Invalid object name '#tempRows'
```

### More Detail
My existing codebase uses Dapper + M$ SQL Server, and includes queries that clone tables from one 'scenario' to another, often using this form:
```
Create Table #tempRows(
   RowIdNew UniqueIdentifier Not Null,
   RowIdOld UniqueIdentifier Not Null,
);

Insert Into #tempRows(RowIdNew, RowIdOld)
Select NewId() as RowIdNew, RowId as RowIdOld
From Rows
Where ScenarioId=@ScidToClone;

Insert Into Rows (ScenarioId, RowId)
Select @ScidNew, RowIdNew
From #tempRows;

-- Cells copy would go here

Drop Table #tempRows
```

**Comment by SabineWren** [comment]
Using a table variable works. `Declare @tempRows Table`. This solves my use case, but it seems like a gap in SqlFun's documentation.

**Comment by jacentino** [comment]
Hi Sabine,

I was not aware of this problem.
After some investigation I realized that it's because SqlFun calls the
query in SchemaOnly mode when generating glue code.
For some reason SqlClient doesn't handle temp tables in SchemaOnly calls
(fortunately, it manages table variables correctly).

Calling queries in SchemaOnly mode is quite an important part of my
approach, thanks to it queries can be tested against typos and type
mismatches without real execution and gives nice equivalent of type safety
(it's described here: https://github.com/jacentino/SqlFun/wiki/Type-safety)

Of course, I'll update the documentation.

Hope, you enjoy working with SqlFun,
Jacek


pt., 17 lut 2023 o 01:38 SabineWren ***@***.***> napisał(a):
