### ISSUE TITLE
Dependency Injection Strategies

### ISSUE THREAD

**Issue by ratsclub** [jacentino/SqlFun#16]
I have been toying around with SqlFun and have some questions regarding its design choices. Considering the README, this is how you are supposed to write code on it:

```fs
module Database =
    // ...
    let createConnection () = new SqliteConnection("Data Source=:memory:")
    let config = createDefaultConfig createConnection
    let runAsync f = AsyncDb.run createConnection f

module Repository =
    open Database
    // ...

    module Account =
        let create: Account -> AsyncDb<Account.Username> =
            sql config "INSERT INTO account (username, password) VALUES (@username, @password) RETURNING username;"
```

In this case, you can see that the module Repository depends on the variable config from the module Database. In this sense, if I were to configure my string connection, I would have something like this:

```fs
module Configuration =
    // imagine some private logic happening here
    let sqlConnection =
        sprintfn "Data Source=%s" config.Database.Host

module Database =
   open Configuration
   // ...
   let createConnection () = new SqliteConnection(sqlConnection)
```

I couldn't figure it out a way to use this library without depending on _module state_. Is there another way to manage the database connection?

Thanks for this awesome library, by the way!

**Comment by jacentino** [comment]
I usually place my connection strings in app.config or appsettings.json and
feel quite comfortable with it.
You can also define some class, instead of a module and make the connection
string its constructor's parameter.

I think there are many more possible scenarios, the one used in readme is
the simplest possible.

pt., 28 kwi 2023 o 15:30 Victor Freire ***@***.***>
napisał(a):

**Comment by ratsclub** [comment]
Hey, thanks for the fast reply!

> You can also define some class, instead of a module and make the connection
string its constructor's parameter.

I tried this but I couldn't find a way to make it fail right at the application startup. I'll keep trying and come back with my solution, thanks!

**Comment by ratsclub** [comment]
So, this was my solution for the time being :smile: 

```fs
module Database =
    let createConnection str () = new SqliteConnection(str)
    let run connection f = DbAction.run connection f

    let sql connection command =
        let config = createDefaultConfig connection
        sql config command

module Workflow =
    module Account =
        type Find = string -> string

module Repository =
    module Account =
        let find connection =
            let query: string -> DbAction<string> = 
                Database.sql connection "select username from account where username = @username"

            fun username -> 
                query username |> Database.run connection
```

**Comment by jacentino** [comment]
Don't do it this way.
Generated queries are not memoized, they are simply assigned to variables,
when defined like this:

module Account =
        let create: Account -> AsyncDb<Account.Username> =
            sql config "INSERT INTO account (username, password)
VALUES ***@***.***, @password) RETURNING username;"

and generated again in each call, when defined this way:

module Account =

        let find connection =
            let query: string -> DbAction<string> =
                Database.sql connection "select username from account
where username = @username"

If you're sure you want to pass a connection string, provide some
memoization.
But in this case your query functions will be generated before the first
use and you lose the quasi static typing, that is, in my opinion, an
important feature of SqlFun.

Additionally - when you call Database.run, a database connection is opened
and closed, so it can be inefficient to run a couple of queries in one
process, constantly opening and closing connections.
If you keep query functions returning DbAction<T> (or AsyncDb<T> when
running asynchronously), you can group them using dbaction (or asyncdb)
monad and call in one open-close cycle, like this:

let userData =
    dbaction {
        let! account = Account.find username
        let! roles = Account.getRoles username
        return account, roles
    } |> Database.run

I think, that if you are really concerned about statically provided
connection string, you have two options:

1. define classes instead of modules (you can even access them via
interfaces), but remember to define queries as member val, not as methods.

2. Provide connection string statically only to sql function (it will be
used only in code generation phase), and by parameter in  run function. In
this case, you can change the database you need to access, but only one
database is used to code generation.

In my opinion the second option is more natural.

pt., 28 kwi 2023 o 21:49 Victor Freire ***@***.***>
napisał(a):

**Comment by ratsclub** [comment]
Thanks for the extensive explanation **and** code review!

> If you're sure you want to pass a connection string, provide some
memoization.

I was able to keep it statically checking with the code below, but you're completely right that I lose the ability to run multiple queries on the same connection. This basically renders the code useless, thanks for noticing it!

```fs
module Database =
    let createConnection str () = new SqliteConnection(str)
    let run connection f = DbAction.run connection f
    let sql connection command =
        let config = createDefaultConfig connection
        sql config command

module Repository =
    module Account =
        let find connection =
            let query: string -> DbAction<string> =
                Database.sql connection "select * from account where username = @username"

            fun username ->
                query username |> Database.run connection

let conn = Database.createConnection "Data Source=:memory:"
let findAccount = Repository.Account.find conn

// use findAccount
```

The thing is, I can't see how to design the code in a way that I won't need to keep the _interface_ signature as `'T -> IDataContext -> 'T`. I'm sorry if this seems like a trivial thing to do, but I was not able to figure it out and others I reached couldn't too. The main use case is to share code that might be used with ASP.NET's dependency injection and without it.

**Comment by ratsclub** [comment]
I gave it another try and this was the solution:

```fs
module Database =
  let createConnection str () = new SqlConnection(str)
  let generatorConfig conn = createDefaultConfig conn
  let sql conn commandText = sql (generatorConfig conn) commandText
  let run connection f = DbAction.run (fun () -> connection) f

module Domain =
  type Customer = { Id: string; Name: string }

module Repository =
  open Database

  type Customer(connStr) =
      member val GetUser: string -> DbAction<Domain.Customer> =
        sql (createConnection connStr) "select id, name from customer where id = @id"

let user = Repository.Customer(connectionStr)
```

In this case, the `Database.run` function is registered as an ASP.NET service that I can call whenever I want.

**Comment by jacentino** [comment]
Hi Victor,

It looks fine to me, there's only one question.
An already created connection is passed to the run function. If you look at
the implementation of DbAction.run function, you can see, that it assumes,
that the connection is created and disposed inside:

let run (createConnection: unit -> #IDbConnection) f =
    let connection = createConnection()
    connection.Open()
    use dc = DataContext.create connection
    f (dc :> IDataContext)

The use statement on DataContext type disposes also the connection. The
question arises, how does your code handle connection?

   - Does it control both: creation and disposal?
   - Does it control opening and closing it?

In general, DbAction.run function was created to encapsulate
connection handling. If you decided to pass a connection to it, you
probably have another idea to handle it.
In this case, you can either define it differently:

let run connection f = f (DataContext.create connection)

eventually, if you want to make it open the connection:

let run connection f =
    connection.Open()
    f (DataContext.create connection)

Or even remove it completely and just register a DataContext object in your
container.
In this case you can simply call your db function by passing datacontext as
an argument, like in code below:

use dataContext = DataContext.create connection
let customer = Customer(<connection string>)
let user = customer.GetUser userId dataContext
...

I also recommend use rather async API, i.e. AsyncDb instead of DbAction.


śr., 14 cze 2023 o 02:03 Victor Freire ***@***.***>
napisał(a):

**Comment by ratsclub** [comment]
Hello, @jacentino. Thanks for the review! I had noticed this problems before but forgot to edit my comment here.

The new version should fix the issues you raised!
