### ISSUE TITLE
AsyncDb helper functions

### ISSUE THREAD

**Issue by SabineWren** [jacentino/SqlFun#22]
Last week I ripped out the last Dapper query in my company's codebase, so we're now entirely using SqlFun. Some helper functions seem to be missing, so I built my own. Either SqlFun should include these functions, or I'm doing something wrong.

SqlFun/SqlFun/DbBuilder.fs module AsyncDb defines a useful 'map' function, but not much else.
```
let map (f: 't1 -> 't2) (v: AsyncDb<'t1>): AsyncDb<'t2> =
   fun ctx -> async {
      let! x = v ctx
      return f x
   }
 ```
 
The SqlFun documentation performs many transforms on multi-result queries, but doesn't remove the Ids used for the joins when denormalizing.
```
let getBlogWithPosts: int -> Blog AsyncDb = 
    sql "select id, name, title, description, owner, 
                createdAt, modifiedAt, modifiedBy 
         from Blog 
         where id = @id;

         select id, blogId, name, title, content, author, 
                createdAt, modifiedAt, modifiedBy, status 
         from post 
         where blogId = @id"
    >> AsyncDb.map (fun b p -> { b with posts = p })
 ```
 This makes sense for some high performance queries, although I remove the Ids when denormalizing to reduce payload size.
 ```
type Cell = { Year: int16; Amount: float }
type Row = { Id: Guid; Cells: Cell[] }
type CellDb =
   { RowId: Guid; Year: int16; Amount: float } with
   static member FromDb(c: CellDb): Cell =
      { Year=c.Year; Amount=c.Amount }

let GetRows: Guid -> AsyncDb<Row seq> =
   let key1 (r: Row) = r.Id
   let key2 (c: CellDb) = c.RowId
   let combine: Row -> CellDb seq -> Row = fun r cs ->
      { r with Cells=cs |> Array.ofSeq |> Array.map CellDb.FromDb }
   Db.Sql "
   Select rows From TableA Where Id=@Id;
   Select cells From TableB Where RowId=@Id;"
   >> Db.Map (Db.Join key1 key2 combine)
 ```
 
For querying records with more complicated nested fields, I find it easier to use nested queries:
 ```
let private getA: CardId -> AsyncDb<TypeA[]> = sql ""
let private getB: CardId -> AsyncDb<TypeB[]> = sql ""
let private cardGet: UserId -> AsyncDb<CardDb[]> = sql ""

let private withFields(card: CardDb) = asyncdb {
   let! a = getA card.Id
   let! b = getB card.Id
   return { card with A=a; B=b }
}
let CardGet(userId: UserId): AsyncDb<Card[]> =
   cardGet userId
   |> Db.BindSequential withFields
   |> Db.MapArray Card.FromDb
````

These functions don't exist in the AsyncDb module, so I'm using an in-house helper module called 'Db':
```
let Bind<'t1,'t2>(f: 't1 -> AsyncDb<'t2>)(x: AsyncDb<'t1>): AsyncDb<'t2> =
   fun ctx -> async {
      let! v = x ctx
      return! (f v) ctx
   }

let MapArray<'t1,'t2>(f: 't1 -> 't2)(x: AsyncDb<'t1[]>): AsyncDb<'t2[]> =
   fun ctx -> async {
      let! vs = x ctx
      return vs |> (Array.map f)
   }

// WARNING -- this requires a SEQUENCE, not an ARRAY
let Sequential<'t1,'t2>(f: 't1 -> AsyncDb<'t2>)(items: seq<'t1>): AsyncDb<'t2[]> =
   fun ctx ->
      items
      |> Seq.map (fun x -> (f x) ctx)
      |> Async.Sequential

let BindSequential<'t1,'t2>(f: 't1 -> AsyncDb<'t2>) = Bind (Sequential f)
```

Is this a gap in SqlFun? If so, are you interested in contributions?

**Comment by jacentino** [comment]
Hi Sabine,

SqlFun has some approach to removing ids. It's explained in [Clean result structures](https://github.com/jacentino/SqlFun/wiki/Clean-result-structures) chapter (maybe the name is not informative enough).

Although, I'm not sure whether it addresses the problem you pointed out. Since unneessary ids are removed at the end of request, the payload size is not reduced, you just get more consistent data.

**Anyway, contributions are, of course welcome:**
* Bind is prefectly ok for me (you could just use asyncdb.Bind, but using function from module instead of computation builder looks better)
* MapArray seems to be shortcut for AsyncDb.map (Array.map f) for me; not sure if it's woth effort, but if you needed it...
* BindSequential is something to analyze carefully

Your example usage of BindSequential introduces so-called [N+1 selects problem](https://stackoverflow.com/questions/97197/what-is-the-n1-selects-problem-in-orm-object-relational-mapping). 
In most cases it causes serious performance problems. Of course, there are legitimate uses - if, e.g. your data contains a few rows with lots of cells, the performance will be ok. But for lots of rows with small number of cells in each row, it will be very inefficient. And, of course, you can simply have no choice, because your payload is so huge, unless you replace guid kyes to ints.

Adding BindSequential to AsyncDb module directly could be misleading for less experienced develpers. I would recommend to add it some special module, or another AsyncDb module in different namespace (fortunately, F# will show functions from both modules, if you make available both of them).

**Comment by SabineWren** [comment]
I hadn't noticed the Clean Results section. That looks like a better solution than using DTOs everywhere.

Now that you mention it, I agree trivial compositions like MapArray and BindSequential don't help much and are more confusing to read than `AsyncDb.map (Array.map f)`.

Sequential is a little more tricky to implement (my version errors on arrays) and putting it in SqlFun would let users run things like `|> AsyncDb.bind (AsyncDb.sequential f)` without having to first define a custom sequential helper.

I see your point about N+1 selects creeping in when Sequential is too convenient. I use SqlFun.Transforms.Standard.join 16 times, and a custom Db.Sequential 24 times. One of those bottlenecks initial page load, while only 11 call into complex queries with a small number of outer rows. Therefore, most of those queries need rewriting to use join.

There are places where Sequential makes perfect sense, such as 2 queries where the outer rows are unit systems (SI vs US Customary), which guarantees exactly 2 outer rows. Others are really complicated and not performance sensitive.

I interpret your proposal like this:
```
let map = //...
let bind = //...
module Slow =
   let sequential = //...
```

That's a good idea, but after thinking about it, I worry it's introducing a footgun that's difficult to remove once people start using it. I can keep relying on a custom sequential function and minimize how often it's used.
