### ISSUE TITLE
CG/SQL implementation 

### ISSUE THREAD

**Issue by ArmanAttaran** [jacentino/SqlFun#3]
Hey !!

sorry to bother you but what do you think about this project or how it would work in a f# project. https://cgsql.dev/

**Comment by jacentino** [comment]
Hi,

Since it's about stored procedures, it should work fine with any language, including F#. 

Improved validation in CG/SQL is a great advantage when using my library. In SqlFun, validation is done by executing queries in SchemaOnly mode and catching exceptions. If you use raw SQLite, it doesn't perform any typecheks, so you're not safe. With CG/SQL you can expect valuable results.

**Comment by ArmanAttaran** [comment]
Thanks !! I guess the performance bonus is not worth the added complexity of using the type provider with sqlite.
