### ISSUE TITLE
Question: sample that controls the SqlConnection

### ISSUE THREAD

**Issue by costa100** [jacentino/SqlFun#6]
Hi,

I noticed that in all your samples that I've seen (see: https://jacentino.github.io/SqlFun/Configuration) you create a function `let createConnection () = new SqlConnection(connectionString)` and everything flows from here. But what if I want to update multiple databases? Do I have to add the set of functions createConnection/generatorConfig/sql/proc for each database in separate modules? It kind of defeats the purpose of functional programming which promotes re-usability. But more likely I am missing something.

Do you have a sample where I have a SqlConnection object and I pass it around to execute different statements?

It tried this:

```
let cn = new SqlConnection(connectionString)
cn.Open()

let getDataList (cn: SqlConnection) : DbAction<DataList array> =
  let config = createDefaultConfig (fun () -> cn) 
  Queries.sql config "select dl.ListCode, dl.ListName from dbo.DataList dl order by 1"


let data2 = getDataList cn |> DbAction.run (fun () -> cn)
data2 |> Array.length |> printfn "%d" 
``` 

but I am getting some weird error:

```
 ---> System.InvalidOperationException: The connection was not closed. The connection's current state is open.
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at SqlFun.Queries.getResultMetadata@354(FSharpFunc`2 createConnection, FSharpFunc`2 createCommand, String commandText, FSharpList`1 paramDefs)
   at SqlFun.Queries.genExecutor@368[a](FSharpFunc`2 createConnection, FSharpFunc`2 createCommand, FSharpOption`1 commandTimeout, FSharpFunc`2 rowBuilder, Boolean makeDiagnosticCalls, String commandText, a createCommand@368, FSharpList`1 paramDefs, Type returnType)
   at SqlFun.Queries.generateSqlCommandCaller(FSharpFunc`2 createConnection, FSharpFunc`2 createCommand, FSharpOption`1 commandTimeout, FSharpFunc`2 extractParameterNames, FSharpFunc`2 paramBuilder, FSharpFunc`2 rowBuilder, Boolean makeDiagnosticCalls, String commandText, Type t)

```

I have to admit, I don't think I understand how SqlFun works. My expectation was to define queries and then run them anyway I want it against a connection object. But it looks like the code tries to figure out at runtime metadata information about the query (structure of the result, parameters) and that fails.

After tweaking the code, this works:
```
let cn = new SqlConnection(designTimeConnectionString)


let getDataList (cn: SqlConnection) : DbAction<DataList array> =
  let config = createDefaultConfig (fun () -> new SqlConnection(connectionString)) 
  Queries.sql config "select dl.ListCode, dl.ListName from dbo.DataList dl order by 1"


let data2 = getDataList cn |> DbAction.run (fun () -> cn)
```

It looks like the connection for the GeneratorConfig has to be independent of the connection that is used to run the queries. I guess it makes sense.

Thanks

**Comment by costa100** [comment]
Ok, I think I figured it out. I can create a DataContext from a SqlConnection object and then I can pass it around when I execute queries.

**Comment by jacentino** [comment]
Hi,

The preferrable way is slightly different.

Firstly, you shouldn't define your function this way:

```fsharp 
let getDataList (cn: SqlConnection) : DbAction<DataList array> =
  let config = createDefaultConfig (fun () -> new SqlConnection(connectionString)) 
  Queries.sql config "select dl.ListCode, dl.ListName from dbo.DataList dl order by 1"
```

It's inefficient, because the data access code is generated each time you invoke it.
Queries.sql doesn't execute your query, it generates a function that executes the query.
It should be defined this way:

let config = createDefaultConfig (fun () -> new SqlConnection(connectionString)) 
let getDataList: DbAction<DataList array> = 
    Queries.sql config "select dl.ListCode, dl.ListName from dbo.DataList dl order by 1"

Then, define your run function:

```fsharp
let run f = DbAction.run (fun () -> new SqlConnection(connectionString)) f
```
And you can invoke getDataList by passing it to run:

```fsharp
let result = getDataList |> run
```
If you need to invoke more functions on one connection, you can use computation expression:

```fsharp
dbaction {
    let! dataList = getDataList |> run
    let! otherStuff = getOtherStuff stuffId |> run
    return dataList, otherStuff 
} |> run
```

If you need to access many databases of the same structure, you should define many "run" functions.

```fsharp
let runA f = DbAction.run (fun () -> new SqlConnection(connectionStringToA)) f
let runB f = DbAction.run (fun () -> new SqlConnection(connectionStringToB)) f
```

Another important thing is, that it's quite common to use async calls for IO intensive tasks. 
Use AsyncDb<_> type and asyncdb computation expression instead of DbAction<_> and dbaction.

You're right, there is a difference between design and runtime connection. It's because there is no way to pass live connection to Queries.sql function in design time.

Hope it helps,
Jacek

**Comment by costa100** [comment]
Closing the issue - thank you for your answer.
